---
- name: Recharger les règles udev
  ansible.builtin.shell: udevadm control --reload-rules && udevadm trigger
  become: true
  changed_when: true

- name: Apply Netplan
  ansible.builtin.command: netplan apply
  become: true
  changed_when: true

- name: Recharger keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: true

- name: Recharger dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true

- name: Recharger radvd
  ansible.builtin.service:
    name: radvd
    state: restarted
    enabled: true
