---
- name: Audit de Sécurité DevSecOps
  hosts: vms
  become: true
  vars_files:
    - .iac_passwd.yaml
  tasks:
    - name: 1. Récupérer l'état des services du système
      ansible.builtin.service_facts:

    - name: 2. Récupérer la configuration SSH
      ansible.builtin.command: sshd -T
      register: sshd_config_dump
      changed_when: false

    - name: 3. Désactiver PermitRootLogin
      ansible.builtin.assert:
        that:
          - "'permitrootlogin no' in sshd_config_dump.stdout"
        success_msg: "Sécurité SSH (1/2) : Root ne peut pas se connecter."
        fail_msg: "VULNÉRABILITÉ : PermitRootLogin n'est pas désactivé !"

    - name: 4. Désactiver PasswordAuthentication
      ansible.builtin.assert:
        that:
          - "'passwordauthentication no' in sshd_config_dump.stdout"
        success_msg: "Sécurité SSH (2/2) : L'authentification par mot de passe est désactivée."
        fail_msg: "VULNÉRABILITÉ : L'authentification par mot de passe est toujours active !"

    - name: 5. Récupérer le statut de UFW
      ansible.builtin.command: ufw status
      register: ufw_status
      changed_when: false

    - name: 6. Vérifier que UFW est bien actif
      ansible.builtin.assert:
        that:
          - "'active' in ufw_status.stdout or 'actif' in ufw_status.stdout"
        success_msg: "Sécurité Réseau : Le pare-feu UFW est bien actif et filtre le trafic."
        fail_msg: "VULNÉRABILITÉ : Le pare-feu UFW n'est pas actif !"

    - name: 7. Installer Lynis pour l'audit de vulnérabilité
      ansible.builtin.apt:
        name: lynis
        state: present
        update_cache: yes

    - name: 8. Lancer un audit Lynis
      ansible.builtin.command: lynis audit system --quick
      register: lynis_result
      changed_when: false
      failed_when: false

    - name: 9. Afficher le score d'audit Lynis
      ansible.builtin.debug:
        msg: "{{ lynis_result.stdout_lines | select('search', 'Hardening index') | list }}"

    - name: 10. Rapport d'Audit Global
      ansible.builtin.debug:
        msg: >
          "Audit DevSecOps terminé avec succès :
           Les politiques de sécurité (SSH durci et UFW actif)
           sont appliquées et vérifiées sur {{ inventory_hostname }}."

    - name: 11. Récupérer le rapport d'Audit Lynis
      ansible.builtin.fetch:
        src: /var/log/lynis-report.dat
        dest: "./reports/lynis-{{ inventory_hostname }}.dat"
        flat: yes
