---
- name: Audit de Sécurité DevSecOps
  hosts: vms
  become: true
  tasks:
    - name: Récupérer l'état des services du système
      ansible.builtin.service_facts:

    - name: Récupérer la configuration SSH effective (active)
      ansible.builtin.command: sshd -T
      register: sshd_config_dump
      changed_when: false

    - name: Valider la désactivation de PermitRootLogin
      ansible.builtin.assert:
        that:
          - "'permitrootlogin no' in sshd_config_dump.stdout"
        success_msg: "Sécurité SSH (1/2) : Root ne peut pas se connecter."
        fail_msg: "VULNÉRABILITÉ : PermitRootLogin n'est pas désactivé !"

    - name: Valider la désactivation de PasswordAuthentication
      ansible.builtin.assert:
        that:
          - "'passwordauthentication no' in sshd_config_dump.stdout"
        success_msg: "Sécurité SSH (2/2) : L'authentification par mot de passe est désactivée."
        fail_msg: "VULNÉRABILITÉ : L'authentification par mot de passe est toujours active !"

    - name: Vérifier que le pare-feu UFW est bien actif
      ansible.builtin.assert:
        that:
          - ansible_facts.services['ufw.service'] is defined
          - ansible_facts.services['ufw.service'].state == 'running'
        success_msg: "Sécurité Réseau : Le pare-feu UFW est bien actif et tourne."
        fail_msg: "VULNÉRABILITÉ : Le service UFW n'est pas en cours d'exécution !"

    - name: Rapport d'Audit
      ansible.builtin.debug:
        msg: >
          "Audit DevSecOps terminé avec succès : 
          Les politiques de sécurité (SSH durci et UFW actif) 
          sont appliquées et vérifiées sur {{ inventory_hostname }}."
