---
- name: Test de l'interconnexion Overlay et du Routage
  hosts: vm-blue
  become: true
  vars_files:
    - .iac_passwd.yaml
  vars:
    target_overlay_ip: "{{ hostvars['vm-green']['overlay_ip_v4'].split('/')[0] }}"
    target_container_ip: "{{ hostvars['vm-green']['my_containers'][0]['ip'] }}"
    target_internet_ip: "8.8.8.8"

  tasks:
    - name: 1. Ping VM Verte
      ansible.builtin.command: ping -c 3 {{ target_overlay_ip }}
      register: ping_vxlan
      changed_when: false

    - name: 2. Ping de blueC0 vers greenDHCP (Inter-site)
      ansible.builtin.command: incus exec blueC0 -- ping -c 3 {{ target_container_ip }}
      register: ping_incus_overlay
      changed_when: false

    - name: 3. Ping Internet depuis blueC0
      ansible.builtin.command: incus exec blueC0 -- ping -c 3 {{ target_internet_ip }}
      register: ping_incus_internet
      changed_when: false

    - name: 4. Afficher le bilan des tests réseau
      ansible.builtin.debug:
        msg: |
          "Tous les tests réseau sont validés avec succès :
           - Le tunnel VXLAN fonctionne (Underlay OVS).
           - Les conteneurs communiquent sur l'Overlay entre les sites.
           - Les conteneurs ont accès à Internet (NAT et NOTRACK OK)."
