---
- name: Provisionnement de l'infrastructure
  hosts: hypervisors
  become: false
  vars_files:
    - /home/etu/.iac_passwd.yaml
  roles:
    - provision_vms

- name: Lancement de la configuration
  import_playbook: site.yaml
