---
- name: Provisionnement de l'infrastructure
  hosts: hypervisors
  become: false
  vars_files:
    - .iac_passwd.yaml
  roles:
    - provision_vms

- name: Lancement de la configuration
  import_playbook: site.yaml

- name: Validation du réseau et de l'interconnexion
  import_playbook: check_network.yaml

- name: Audit de Sécurité DevSecOps
  import_playbook: check_security.yaml
