---
- name: PLAY 1 - Préparation et récupération des clés SSH
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: 1. Enregistrer l'IP de DevNet
      ansible.builtin.set_fact:
        devnet_ip: "{{ ansible_default_ipv4.address }}"

    - name: 2. Attendre que le port SSH soit ouvert sur les VMs
      ansible.builtin.wait_for:
        host: "{{ hostvars[item].ansible_host }}"
        port: 22
        state: started
        delay: 5
        timeout: 60
      loop: "{{ groups['vms'] }}"

    - name: 3. Scanner et ajouter les empreintes SSH aux known_hosts
      ansible.builtin.known_hosts:
        name: "{{ hostvars[item].ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H -t ed25519 ' + hostvars[item].ansible_host) }}"
        state: present
      loop: "{{ groups['vms'] }}"

- name: PLAY 2 - Amorçage de la Passerelle (VM Rouge)
  hosts: router
  become: true
  vars_files: [.iac_passwd.yaml]
  roles:
    - common_sec
    - network_router

- name: PLAY 3 - Configuration des Tenants (Overlay et Services)
  hosts: tenants
  become: true
  vars_files: [.iac_passwd.yaml]
  roles:
    - common_sec
    - network_tenant
    - incus
