---
all:
  children:
    hypervisors:
      hosts:
        oscar:
          ansible_host: oscar6
      vars:
        ansible_ssh_user: "{{ hypervisor_user }}"
        ansible_ssh_pass: "{{ hypervisor_pass }}"
        ansible_ssh_port: 2222
    vms:
      children:
        router:
          hosts:
            vm-red:
              ansible_host: 10.0.128.66
        tenants:
          hosts:
            vm-blue:
              ansible_host: 172.18.169.10
            vm-green:
              ansible_host: 172.18.170.10
