---
- name: Redémarrer SSH
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Recharger UFW
  community.general.ufw:
    state: reloaded

- name: Redémarrer Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
