---
- name: 1. Installer les paquets necessaires
  ansible.builtin.apt:
    name:
      - ufw
      - tcpdump
      - vim
      - curl
      - ethtool
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: 2. Sécuriser la configuration SSH
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/99-ansible-hardening.conf
    content: |
      PermitRootLogin {{ permit_root_login | default('no') }}
      PasswordAuthentication {{ password_authentication | default('no') }}
    mode: '0600'
  notify: Redémarrer SSH

- name: 3. UFW - Autoriser SSH depuis DevNet
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port | default('22') }}"
    proto: tcp
    src: "{{ hostvars['localhost']['devnet_ip'] }}"
  notify: Recharger UFW

- name: 4. Activer UFW et définir la politique par défaut
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
