---
- name: 1. Installer les paquets
  ansible.builtin.apt:
    name:
      - openvswitch-switch
      - radvd
    state: present
    update_cache: true

- name: 2. Correction du bug réseau VXLAN (udev)
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/99-net-offload.rules
    content: |
      ACTION=="add", SUBSYSTEM=="net", KERNEL=="veth*", RUN+="/sbin/ethtool -K $name tx off"
      ACTION=="add", SUBSYSTEM=="net", KERNEL=="vxlan*", RUN+="/sbin/ethtool -K $name tx off"
    mode: '0644'
  notify: Recharger les règles udev

- name: 3. Activer le routage IP
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: 4. Appliquer la configuration réseau Netplan
  ansible.builtin.template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    mode: '0600'
  notify: Apply Netplan

- name: 4.1. Configurer radvd pour les annonces IPv6 (SLAAC)
  ansible.builtin.template:
    src: radvd.j2
    dest: /etc/radvd.conf
  notify: Recharger radvd

- name: 4.2. Activer et démarrer le service radvd
  ansible.builtin.service:
    name: radvd
    state: started
    enabled: true

- name: 5. UFW - Autoriser le trafic Underlay (Inter-VMs)
  community.general.ufw:
    rule: allow
    src: 172.18.0.0/16

- name: 6. UFW - Autoriser le trafic Overlay IPv4 & IPv6 (Conteneurs INPUT)
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
  loop:
    - 192.0.2.0/24
    - 2001:db8:683::/64

- name: 7. UFW - Autoriser le trafic Overlay IPv4 & IPv6 (Conteneurs FORWARD)
  community.general.ufw:
    rule: allow
    route: true
    src: "{{ item }}"
  loop:
    - 192.0.2.0/24
    - 2001:db8:683::/64

- name: 7.1. UFW - Autoriser le trafic retour d'Internet vers Overlay (Routage asymétrique)
  community.general.ufw:
    rule: allow
    route: true
    dest: "{{ item }}"
  loop:
    - 192.0.2.0/24
    - 2001:db8:683::/64

- name: 8. UFW - Autoriser le trafic Overlay (SLAAC/ICMPv6 et DHCP)
  community.general.ufw:
    rule: allow
    direction: in
    interface: "{{ item }}"
  loop:
    - "{{ ovs_bridge_name }}"
    - "vxlanGreenBlue"

- name: 9. UFW - Autoriser les interfaces locales (Bridge et VXLAN)
  community.general.ufw:
    rule: allow
    interface: "{{ item }}"
    direction: in
  loop:
    - "{{ ovs_bridge_name }}"
    - "vxlanGreenBlue"

- name: 10. Forcer l'application du réseau avant de passer à Incus
  ansible.builtin.meta: flush_handlers
