---
- name: S'assurer que le paquet openvswitch-switch est installé
  apt:
    name: openvswitch-switch
    state: present

- name: Générer la configuration Netplan pour le routeur (Rouge)
  template:
    src: netplan-router.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == 'vm-red'
  notify: apply netplan

- name: Générer la configuration Netplan pour les tenants (Bleu/Vert)
  template:
    src: netplan-tenant.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in ['vm-blue', 'vm-green']
  notify: apply netplan
