---
vm_name: bleueVM
tapnum: 241
master_image: debian-testing-amd64.qcow2

underlay_vlan: 681
underlay_ip: 172.18.169.10
underlay_cidr: 24
underlay_gw: 172.18.169.1

vxlan_id: 683
vxlan_remote_ip: 172.18.170.10 # IP VM Verte
ovs_bridge_name: C-3PO
overlay_ip_v4: 192.0.2.1/24
overlay_ip_v6: "2001:db8:683::2/64"
overlay_gw_v4: 192.0.2.1
overlay_local_ip: "10.50.0.252/24"
overlay_mtu: 1450

keepalived_state: "MASTER"
keepalived_priority: 100
underlay_sync_ip: "192.0.2.1"
peer_sync_ip: "192.0.2.2"

my_containers:
  - name: blueDHCP
    type: dhcp
    ip: 192.0.2.250
    dhcp_range: "192.0.2.50,192.0.2.99"
  - name: blueC0
    type: client
  - name: blueC1
    type: client
  - name: blueC2
    type: client
