---
vm_name: bleueVM
tapnum: 241
master_image: debian-testing-amd64.qcow2

underlay_vlan: 681
underlay_ip: 172.18.169.10
underlay_cidr: 24
underlay_gw: 172.18.169.1

vxlan_id: 683
vxlan_remote_ip: 172.18.170.10 # IP VM Verte
ovs_bridge_name: C-3PO-BLUE
overlay_ip_v4: 192.0.2.1/24
overlay_ip_v6: "2001:db8:683::2/64"
overlay_mtu: 1450
