---
vm_name: verteVM
tapnum: 242
master_image: debian-testing-amd64.qcow2

underlay_vlan: 682
underlay_ip: 172.18.170.10
underlay_cidr: 24
underlay_gw: 172.18.170.1

vxlan_id: 1234
vxlan_remote_ip: 172.18.169.10 # IP VM Bleue
ovs_bridge_name: C-3PO-GREEN
overlay_ip_v4: 192.0.2.2/24
overlay_ip_v6: "2001:db8:683::1/64" # Attention conflit IP
overlay_mtu: 1500
