---
vm_name: verteVM
tapnum: 242
master_image: debian-testing-amd64.qcow2

underlay_vlan: 682
underlay_ip: 172.18.170.10
underlay_cidr: 24
underlay_gw: 172.18.170.1

vxlan_id: 683
vxlan_remote_ip: 172.18.169.10 # IP VM Bleue
ovs_bridge_name: C-3PO
overlay_ip_v4: 192.0.2.2/24
overlay_ip_v6: "2001:db8:683::1/64"
overlay_gw_v4: 192.0.2.2
overlay_local_ip: "10.50.0.253/24"
overlay_mtu: 1450

keepalived_state: "BACKUP"
keepalived_priority: 90
dhcp_peer_role: "secondary"
underlay_sync_ip: "192.0.2.2"
peer_sync_ip: "192.0.2.1"

my_containers:
  - name: greenDHCP
    type: dhcp
    ip: 192.0.2.251
    dhcp_range: "192.0.2.10,192.0.2.49"
  - name: greenC0
    type: client
  - name: greenC1
    type: client
