name: CI DevSecOps Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout du code
        uses: actions/checkout@v4

      - name: 2. Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 4. Installer les dépendances Python et Ansible
        run: |
          pip install -r requirements.txt
          pip install ansible-lint
          ansible-galaxy collection install -r requirements.yaml

      - name: 5. Créer les fichiers secrets factices pour la CI
        run: |
          touch .vault_pass.txt
          touch .iac_passwd.yaml

      - name: 6. Run Ansible Lint
        run: ansible-lint -c .ansible-lint

      - name: 7. Run Checkov (SAST IaC)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: ansible
          quiet: true
          skip_path: ".iac_passwd.yaml"
