name: CI DevSecOps Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Créer un faux fichier vault
        run: |
          sed -i '/vault_password_file/d' ansible.cfg
          sudo mkdir -p /home/etu
          sudo touch /home/etu/.vault_pass.txt

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances Ansible
        run: |
          pip install ansible-core
          ansible-galaxy collection install community.general

      - name: Run Ansible Lint
        uses: ansible/ansible-lint@main

      - name: Run Checkov
        uses: bridgecrewio/checkov@main
        with:
          framework: ansible
          quiet: true
          skip_path: "group_vars/all/vault.yaml"
