---
- name: 0. Installer le paquet Incus
  ansible.builtin.apt:
    name: incus
    state: present
    update_cache: true

- name: 1. Initialiser Incus
  ansible.builtin.command: incus admin init --minimal
  args:
    creates: /var/lib/incus/cluster.crt

- name: 2. Vérifier le bridge OVS
  ansible.builtin.command: incus profile show default
  register: incus_profile_output
  changed_when: false

- name: 3. Configurer le bridge OVS
  ansible.builtin.shell: |
    incus profile device remove default eth0 || true
    incus profile device add default eth0 nic nictype=bridged parent={{ ovs_bridge_name }} mtu={{ overlay_mtu }}
  when: "ovs_bridge_name not in incus_profile_output.stdout"

- name: 4. Vérifier les conteneurs
  ansible.builtin.command: incus list -c n --format csv
  register: incus_list
  changed_when: false

- name: 5. Lancer les conteneurs Alpine
  ansible.builtin.command: "incus launch images:alpine/edge {{ item.name }}"
  loop: "{{ my_containers }}"
  when: "item.name not in incus_list.stdout"

- name: 6. Injecter la configuration réseau
  ansible.builtin.shell:
    cmd: |
      incus exec {{ item.name }} -- sysctl -w net.ipv6.conf.eth0.accept_ra=2
      cat <<EOF | incus file push - {{ item.name }}/etc/network/interfaces
      auto lo
      iface lo inet loopback

      auto eth0
      {% if item.type == 'dhcp' %}
      iface eth0 inet static
          address {{ item.ip }}/24
          gateway {{ overlay_gw_v4 }}
      {% else %}
      iface eth0 inet dhcp
      {% endif %}
      EOF
  loop: "{{ my_containers }}"

- name: 7. Redémarrer les serveurs DHCP pour appliquer l'IP statique
  ansible.builtin.command: incus restart {{ item.name }}
  loop: "{{ my_containers }}"
  when: item.type == 'dhcp'

- name: 8. Attendre 3 secondes
  ansible.builtin.wait_for:
    timeout: 3
  delegate_to: localhost
- name: 9. Installer et configurer dnsmasq
  ansible.builtin.shell:
    cmd: |
      incus exec {{ item.name }} -- sh -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
      incus exec {{ item.name }} -- apk update
      incus exec {{ item.name }} -- apk add dnsmasq
      cat <<EOF | incus file push - {{ item.name }}/etc/dnsmasq.conf
      interface=eth0
      port=0
      dhcp-range={{ item.dhcp_range }},255.255.255.0,12h
      dhcp-option=option:router,{{ overlay_gw_v4 }}
      dhcp-option=option:dns-server,8.8.8.8
      EOF
      incus exec {{ item.name }} -- rc-update add dnsmasq default
      incus exec {{ item.name }} -- rc-service dnsmasq restart || /etc/init.d/dnsmasq restart
  loop: "{{ my_containers }}"
  when: item.type == 'dhcp'

- name: 10. Redémarrer les clients pour qu'ils obtiennent une IP via DHCP
  ansible.builtin.command: incus restart {{ item.name }}
  loop: "{{ my_containers }}"
  when: item.type == 'client'
