---
- name: 1. Vérifier l'installation d'Incus
  ansible.builtin.apt:
    name: incus
    state: present

- name: 2. Initialiser Incus
  ansible.builtin.command: incus admin init --minimal
  args:
    creates: /var/lib/incus/cluster.crt
  when: inventory_hostname in ['vm-blue', 'vm-green']

- name: 3. Supprimer l'ancienne carte eth0
  ansible.builtin.command: incus profile device remove default eth0
  failed_when: false
  changed_when: false
  when: inventory_hostname in ['vm-blue', 'vm-green']

- name: 4. Créer la carte eth0 attachée au bridge OVS
  ansible.builtin.command: "incus profile device add default eth0 nic nictype=bridged parent={{ ovs_bridge_name }} mtu={{ overlay_mtu }}"
  register: profile_add
  changed_when: profile_add.rc == 0
  when: inventory_hostname in ['vm-blue', 'vm-green']

- name: 5. Définir la topologie des conteneurs pour la VM Bleue
  ansible.builtin.set_fact:
    my_containers:
      - { name: 'blueC0', ip: '192.0.2.60' }
      - { name: 'blueC1', ip: '192.0.2.53' }
      - { name: 'blueC2', ip: '192.0.2.59' }
      - { name: 'blueDHCP', ip: '192.0.2.250' }
  when: inventory_hostname == 'vm-blue'

- name: 6. Définir la topologie des conteneurs pour la VM Verte
  ansible.builtin.set_fact:
    my_containers:
      - { name: 'greenC0', ip: '192.0.2.19' }
      - { name: 'greenC1', ip: '192.0.2.20' }
      - { name: 'greenDHCP', ip: '192.0.2.251' }
  when: inventory_hostname == 'vm-green'

- name: 7. Lancer les conteneurs
  ansible.builtin.command: "incus launch images:alpine/edge {{ item.name }}"
  args:
    creates: "/var/log/incus/{{ item.name }}"
  loop: "{{ my_containers }}"
  when: inventory_hostname in ['vm-blue', 'vm-green']

- name: 8. Configurer le réseau (IPAM) via injection de fichiers (Version simplifiée)
  ansible.builtin.shell: |
    # Injection du fichier interfaces
    echo "auto lo
    iface lo inet loopback

    auto eth0
    iface eth0 inet static
        address {{ item.ip }}
        netmask 255.255.255.0
        gateway 192.0.2.{{ '1' if inventory_hostname == 'vm-blue' else '2' }}" | incus file push - {{ item.name }}/etc/network/interfaces

    # Injection DNS
    echo "nameserver 8.8.8.8" | incus file push - {{ item.name }}/etc/resolv.conf

    # Redémarrage pour appliquer
    incus restart {{ item.name }}
  loop: "{{ my_containers }}"
  when: inventory_hostname in ['vm-blue', 'vm-green']
  changed_when: true
